import { type Period, periodStart } from './period.js'

/** What a threshold does when its budget is reached.
 *  - 'alert': notify the user, keep running.
 *  - 'block': hard stop — fail the activation, send a stop message, halt the loop. */
export type ThresholdAction = 'alert' | 'block'

/** A user-configured spend cap. The threshold checker fires when total
 *  cost in `period` (in the configured timezone) reaches `amountUsd`. */
export interface UsageThreshold {
  id: string                  // 'threshold_<timestamp>_<random>' — generated by addThreshold
  period: Period              // 'day' | 'week' | 'month' (reused from period.ts)
  amountUsd: number           // dollar amount that triggers the alert
  action: ThresholdAction     // 'alert' (notify) or 'block' (hard stop)
}

/** A threshold that has crossed and is eligible to fire this period.
 *  Includes the full threshold record so callers (task 7's delivery) can
 *  compose user-facing messages without re-looking-up by id. */
export interface ThresholdCrossing {
  threshold: UsageThreshold
  currentSpend: number   // total spend in the threshold's period (USD)
  periodStart: Date      // UTC instant of the current period's local-midnight start
}

/** A threshold decorated with its current period spend, returned by the
 *  GET /api/usage/thresholds endpoint to power the dashboard "currently at"
 *  display. `periodStart` is an ISO 8601 string because it crosses the
 *  JSON boundary to the front-end. */
export interface ThresholdWithSpend extends UsageThreshold {
  currentSpend: number
  periodStart: string
}

/** Decorate each threshold with its current period spend.
 *  Pure function — no I/O. Caller binds `getCostSince` to the UsageStore. */
export function enrichThresholds(
  thresholds: UsageThreshold[],
  getCostSince: (since: Date) => number,
  now: Date,
  tz: string,
): ThresholdWithSpend[] {
  return thresholds.map(t => {
    const start = periodStart(tz, t.period, now)
    return {
      ...t,
      currentSpend: getCostSince(start),
      periodStart: start.toISOString(),
    }
  })
}

export interface CheckThresholdsInput {
  thresholds: UsageThreshold[]
  firedAt: Record<string, Date>          // from AppStateStore.getAllThresholdFiredAt()
  getCostSince: (since: Date) => number  // bound to UsageStore.getCostSince
  now: Date                              // explicit, plumbed from caller (no `new Date()` default)
  tz: string                             // configured timezone, e.g. 'America/New_York'
}

const PERIOD_ADJECTIVE: Record<Period, string> = {
  day: 'daily',
  week: 'weekly',
  month: 'monthly',
}

const PERIOD_PHRASE: Record<Period, string> = {
  day: 'today',
  week: 'this week',
  month: 'this month',
}

/** Format a threshold crossing as a user-facing alert message.
 *  Example: `Heads up — you've hit your monthly budget "Coffee budget" of $100.00. So far this month: $103.42.` */
export function formatThresholdAlert(crossing: ThresholdCrossing): string {
  const { threshold, currentSpend } = crossing
  const adj = PERIOD_ADJECTIVE[threshold.period]
  const phrase = PERIOD_PHRASE[threshold.period]
  return `Heads up — you've hit your ${adj} budget of $${threshold.amountUsd.toFixed(2)}. So far ${phrase}: $${currentSpend.toFixed(2)}.`
}

/** Format a block-action threshold crossing as a user-facing stop message.
 *  Tells the user the two genuine ways to resume (raise the cap or wait for
 *  rollover) and confirms that their message has been preserved across the
 *  block — task 10's release-not-fail semantics. */
export function formatThresholdBlock(crossing: ThresholdCrossing): string {
  const { threshold, currentSpend } = crossing
  const adj = PERIOD_ADJECTIVE[threshold.period]
  const phrase = PERIOD_PHRASE[threshold.period]
  return `⚠️ Shrok has stopped. Your ${adj} budget of $${threshold.amountUsd.toFixed(2)} was reached (so far ${phrase}: $${currentSpend.toFixed(2)}). To resume: raise the threshold in the dashboard or wait for the period to roll over, then restart Shrok. Your message has been preserved and will be processed when you do.`
}

// Internal — route handlers consume via control-flow (`if (!result.ok)`),
// not by name. TypeScript infers the shape from each function's return type
// and propagates it through the discriminated narrowing without callers
// needing to import the type.
type ValidationResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: string }

const PERIODS: ReadonlySet<Period> = new Set<Period>(['day', 'week', 'month'])
const ACTIONS: ReadonlySet<ThresholdAction> = new Set<ThresholdAction>(['alert', 'block'])
/** Validate a body for POST /api/usage/thresholds. All fields required. */
export function validateCreateThreshold(body: unknown): ValidationResult<Omit<UsageThreshold, 'id'>> {
  if (!body || typeof body !== 'object') return { ok: false, error: 'body must be an object' }
  const b = body as Record<string, unknown>

  if (typeof b['period'] !== 'string' || !PERIODS.has(b['period'] as Period)) {
    return { ok: false, error: "period must be 'day', 'week', or 'month'" }
  }
  if (typeof b['amountUsd'] !== 'number' || !Number.isFinite(b['amountUsd']) || b['amountUsd'] <= 0) {
    return { ok: false, error: 'amountUsd must be a positive finite number' }
  }
  // action is optional in the body — defaults to 'alert' if missing.
  let action: ThresholdAction = 'alert'
  if ('action' in b) {
    if (typeof b['action'] !== 'string' || !ACTIONS.has(b['action'] as ThresholdAction)) {
      return { ok: false, error: "action must be 'alert' or 'block'" }
    }
    action = b['action'] as ThresholdAction
  }

  return { ok: true, value: { period: b['period'] as Period, amountUsd: b['amountUsd'], action } }
}

/** Validate a body for PATCH /api/usage/thresholds/:id. All fields optional, but at least one required. */
export function validateUpdateThreshold(body: unknown): ValidationResult<Partial<Omit<UsageThreshold, 'id'>>> {
  if (!body || typeof body !== 'object') return { ok: false, error: 'body must be an object' }
  const b = body as Record<string, unknown>
  const patch: Partial<Omit<UsageThreshold, 'id'>> = {}

  if ('period' in b) {
    if (typeof b['period'] !== 'string' || !PERIODS.has(b['period'] as Period)) {
      return { ok: false, error: "period must be 'day', 'week', or 'month'" }
    }
    patch.period = b['period'] as Period
  }
  if ('amountUsd' in b) {
    if (typeof b['amountUsd'] !== 'number' || !Number.isFinite(b['amountUsd']) || b['amountUsd'] <= 0) {
      return { ok: false, error: 'amountUsd must be a positive finite number' }
    }
    patch.amountUsd = b['amountUsd']
  }
  if ('action' in b) {
    if (typeof b['action'] !== 'string' || !ACTIONS.has(b['action'] as ThresholdAction)) {
      return { ok: false, error: "action must be 'alert' or 'block'" }
    }
    patch.action = b['action'] as ThresholdAction
  }

  if (Object.keys(patch).length === 0) {
    return { ok: false, error: 'patch must include at least one of period, amountUsd, action' }
  }
  return { ok: true, value: patch }
}

/** Returns alert-action thresholds that have crossed and not already fired
 *  this period. Pure function — no I/O, no side effects. The caller is
 *  responsible for stamping fired state (via setThresholdFiredAt) and
 *  delivering alerts. Block-action thresholds are filtered out — they're
 *  handled separately by `findBlockingThresholds` (no fired-state filtering). */
export function checkThresholds(input: CheckThresholdsInput): ThresholdCrossing[] {
  const crossings: ThresholdCrossing[] = []
  for (const threshold of input.thresholds) {
    if (threshold.action !== 'alert') continue   // blocks are handled by findBlockingThresholds

    const start = periodStart(input.tz, threshold.period, input.now)

    // Eligibility: skip if already fired in the current period.
    // Compare via .getTime() so we're not relying on Date's implicit valueOf coercion.
    const lastFired = input.firedAt[threshold.id]
    if (lastFired && lastFired.getTime() > start.getTime()) continue

    // Crossed: skip if current spend hasn't reached the threshold
    const spend = input.getCostSince(start)
    if (spend < threshold.amountUsd) continue

    crossings.push({ threshold, currentSpend: spend, periodStart: start })
  }
  return crossings
}

/** Returns block-action thresholds whose current spend is at or over their
 *  amountUsd. Unlike `checkThresholds`, this does NOT filter by fired-state —
 *  a block must trigger every check while spend is over budget, including
 *  after restart, until the period rolls over or the user raises the cap. */
export function findBlockingThresholds(
  thresholds: UsageThreshold[],
  getCostSince: (since: Date) => number,
  now: Date,
  tz: string,
): ThresholdCrossing[] {
  const result: ThresholdCrossing[] = []
  for (const t of thresholds) {
    if (t.action !== 'block') continue
    const start = periodStart(tz, t.period, now)
    const spend = getCostSince(start)
    if (spend >= t.amountUsd) {
      result.push({ threshold: t, currentSpend: spend, periodStart: start })
    }
  }
  return result
}
